name: Plugins - CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    permissions:
      contents: read
      id-token: write
    name: CI
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@33cae1f950c4f76df8827a183bda17c6f8a51e45 # ci-cd-workflows/v9.0.0
    with:
      plugin-version-suffix: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
      run-playwright: true
